# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS build

# Install dependencies for building
WORKDIR /app
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Install build dependencies
RUN npm install --ignore-scripts && npm run build

# Prepare production image
FROM node:lts-alpine
WORKDIR /app

# Copy built files and install runtime dependencies
COPY --from=build /app/build ./build
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts && apk add --no-cache ca-certificates

# Set default workdir and entrypoint
WORKDIR /app
ENTRYPOINT ["node", "build/index.js"]
